# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
