# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=5000)),
                ('reciever', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('sub', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
